services:
  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: biblioteca
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: biblioteca-api
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    command: npm run dev

volumes:
  postgres_data:
